name: LvL_Bank
version: 1.0_Beta
main: me.davi2206.LvLBank.Enable_LvL_Bank

commands:
    lvlBank:
        usage: /<command>
        description: Handels all LvL_Bank commands
        aliases: [lvl, lvl_bank]