name: LvL_Bank
version: 0.5
main: me.davi2206.LvLBank.Enable_LvL_Bank

commands:
    lvlBank:
        usage: /<command>
        description: Handels all LvL_Bank commands
        aliases: [lvl, lvl_bank]
    Transferetoyml:
        usage: /<command>
        description: Moves bank data from database to YML file